ALTER TABLE IF EXISTS users
ADD COLUMN IF NOT EXISTS reverse_enabled BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE IF EXISTS words
ADD COLUMN IF NOT EXISTS last_answer_is_original BOOLEAN NOT NULL DEFAULT TRUE;
